/**
 * Supabase Auto-Generated Types
 *
 * This file is auto-generated by the Supabase CLI and GitHub Actions CI/CD.
 * DO NOT EDIT MANUALLY - changes will be overwritten on the next deployment.
 *
 * To regenerate locally:
 *   npx supabase gen types typescript --project-id ennftfzkajmgsmjmfcbv > src/types/supabase-generated.ts
 *
 * Or using npm script:
 *   npm run supabase:types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          plan: 'starter' | 'pro' | 'premium' | 'copilot'
          plan_started_at: string | null
          plan_expires_at: string | null
          stripe_customer_id: string | null
          is_active: boolean
          role: 'user' | 'admin'
          niche: string | null
          preferred_tone: 'formal' | 'casual' | 'direct'
          onboarding_completed: boolean
          xp_points: number
          level: 'iniciante' | 'vendedor' | 'closer' | 'topseller' | 'elite'
          current_streak: number
          longest_streak: number
          ai_credits_remaining: number
          ai_credits_monthly: number
          saved_variables: Json
          push_subscription: Json | null
          notification_prefs: Json
          referral_code: string | null
          referred_by: string | null
          webhook_source: string | null
          password_changed: boolean
          last_login_at: string | null
          active_days: number
          new_level: string
          cyclic_xp: number
          bonus_scripts: number
          streak_reward_pending: boolean
          last_active_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string
          plan?: 'starter' | 'pro' | 'premium' | 'copilot'
          plan_started_at?: string | null
          plan_expires_at?: string | null
          stripe_customer_id?: string | null
          is_active?: boolean
          role?: 'user' | 'admin'
          niche?: string | null
          preferred_tone?: 'formal' | 'casual' | 'direct'
          onboarding_completed?: boolean
          xp_points?: number
          level?: 'iniciante' | 'vendedor' | 'closer' | 'topseller' | 'elite'
          current_streak?: number
          longest_streak?: number
          ai_credits_remaining?: number
          ai_credits_monthly?: number
          saved_variables?: Json
          push_subscription?: Json | null
          notification_prefs?: Json
          referral_code?: string | null
          referred_by?: string | null
          webhook_source?: string | null
          password_changed?: boolean
          last_login_at?: string | null
          active_days?: number
          new_level?: string
          cyclic_xp?: number
          bonus_scripts?: number
          streak_reward_pending?: boolean
          last_active_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          plan?: 'starter' | 'pro' | 'premium' | 'copilot'
          plan_started_at?: string | null
          plan_expires_at?: string | null
          stripe_customer_id?: string | null
          is_active?: boolean
          role?: 'user' | 'admin'
          niche?: string | null
          preferred_tone?: 'formal' | 'casual' | 'direct'
          onboarding_completed?: boolean
          xp_points?: number
          level?: 'iniciante' | 'vendedor' | 'closer' | 'topseller' | 'elite'
          current_streak?: number
          longest_streak?: number
          ai_credits_remaining?: number
          ai_credits_monthly?: number
          saved_variables?: Json
          push_subscription?: Json | null
          notification_prefs?: Json
          referral_code?: string | null
          referred_by?: string | null
          webhook_source?: string | null
          password_changed?: boolean
          last_login_at?: string | null
          active_days?: number
          new_level?: string
          cyclic_xp?: number
          bonus_scripts?: number
          streak_reward_pending?: boolean
          last_active_date?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      script_categories: {
        Row: {
          id: string
          name: string
          slug: string
          description: string
          icon: string
          color: string
          display_order: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description: string
          icon?: string
          color?: string
          display_order?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string
          icon?: string
          color?: string
          display_order?: number
          is_active?: boolean
          created_at?: string
        }
      }
      scripts: {
        Row: {
          id: string
          category_id: string
          title: string
          content: string
          content_formal: string | null
          content_direct: string | null
          context_description: string
          objection_keywords: string[]
          objection_embedding: number[] | null
          audio_url: string | null
          tags: string[]
          min_plan: 'starter' | 'pro' | 'premium' | 'copilot'
          is_ai_generated: boolean
          generated_by_user_id: string | null
          display_order: number
          is_active: boolean
          global_usage_count: number
          global_effectiveness: number
          global_conversion_rate: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          category_id: string
          title: string
          content: string
          content_formal?: string | null
          content_direct?: string | null
          context_description?: string
          objection_keywords?: string[]
          objection_embedding?: number[] | null
          audio_url?: string | null
          tags?: string[]
          min_plan?: 'starter' | 'pro' | 'premium' | 'copilot'
          is_ai_generated?: boolean
          generated_by_user_id?: string | null
          display_order?: number
          is_active?: boolean
          global_usage_count?: number
          global_effectiveness?: number
          global_conversion_rate?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          category_id?: string
          title?: string
          content?: string
          content_formal?: string | null
          content_direct?: string | null
          context_description?: string
          objection_keywords?: string[]
          objection_embedding?: number[] | null
          audio_url?: string | null
          tags?: string[]
          min_plan?: 'starter' | 'pro' | 'premium' | 'copilot'
          is_ai_generated?: boolean
          generated_by_user_id?: string | null
          display_order?: number
          is_active?: boolean
          global_usage_count?: number
          global_effectiveness?: number
          global_conversion_rate?: number
          created_at?: string
          updated_at?: string
        }
      }
      script_usage: {
        Row: {
          id: string
          user_id: string
          script_id: string
          lead_id: string | null
          tone_used: 'formal' | 'casual' | 'direct' | null
          used_at: string
          effectiveness_rating: number | null
          resulted_in_sale: boolean | null
          sale_value: number | null
          feedback_note: string | null
        }
        Insert: {
          id?: string
          user_id: string
          script_id: string
          lead_id?: string | null
          tone_used?: 'formal' | 'casual' | 'direct' | null
          used_at?: string
          effectiveness_rating?: number | null
          resulted_in_sale?: boolean | null
          sale_value?: number | null
          feedback_note?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          script_id?: string
          lead_id?: string | null
          tone_used?: 'formal' | 'casual' | 'direct' | null
          used_at?: string
          effectiveness_rating?: number | null
          resulted_in_sale?: boolean | null
          sale_value?: number | null
          feedback_note?: string | null
        }
      }
      leads: {
        Row: {
          id: string
          user_id: string
          name: string
          phone: string | null
          stage: 'novo' | 'abordado' | 'qualificado' | 'proposta' | 'fechado' | 'perdido'
          expected_value: number | null
          conversation_history: Json
          notes: string | null
          last_contact_at: string | null
          next_followup_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          phone?: string | null
          stage?: 'novo' | 'abordado' | 'qualificado' | 'proposta' | 'fechado' | 'perdido'
          expected_value?: number | null
          conversation_history?: Json
          notes?: string | null
          last_contact_at?: string | null
          next_followup_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          phone?: string | null
          stage?: 'novo' | 'abordado' | 'qualificado' | 'proposta' | 'fechado' | 'perdido'
          expected_value?: number | null
          conversation_history?: Json
          notes?: string | null
          last_contact_at?: string | null
          next_followup_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      webhook_logs: {
        Row: {
          id: string
          source: string
          event_type: 'purchase' | 'upgrade' | 'cancel'
          payload: Json
          email_extracted: string
          status: string
          plan_granted: string | null
          user_created: boolean
          user_id: string | null
          error_message: string | null
          processed_at: string
        }
        Insert: {
          id?: string
          source: string
          event_type: 'purchase' | 'upgrade' | 'cancel'
          payload: Json
          email_extracted: string
          status?: string
          plan_granted?: string | null
          user_created?: boolean
          user_id?: string | null
          error_message?: string | null
          processed_at?: string
        }
        Update: {
          id?: string
          source?: string
          event_type?: 'purchase' | 'upgrade' | 'cancel'
          payload?: Json
          email_extracted?: string
          status?: string
          plan_granted?: string | null
          user_created?: boolean
          user_id?: string | null
          error_message?: string | null
          processed_at?: string
        }
      }
      daily_challenges: {
        Row: {
          id: string
          user_id: string
          challenge_date: string
          challenge_type: string
          target_count: number
          current_count: number
          completed: boolean
          xp_reward: number
        }
        Insert: {
          id?: string
          user_id: string
          challenge_date: string
          challenge_type: string
          target_count?: number
          current_count?: number
          completed?: boolean
          xp_reward?: number
        }
        Update: {
          id?: string
          user_id?: string
          challenge_date?: string
          challenge_type?: string
          target_count?: number
          current_count?: number
          completed?: boolean
          xp_reward?: number
        }
      }
      user_badges: {
        Row: {
          id: string
          user_id: string
          badge_type: string
          badge_name: string
          earned_at: string
        }
        Insert: {
          id?: string
          user_id: string
          badge_type: string
          badge_name: string
          earned_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          badge_type?: string
          badge_name?: string
          earned_at?: string
        }
      }
      user_collections: {
        Row: {
          id: string
          user_id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          created_at?: string
        }
      }
      collection_scripts: {
        Row: {
          collection_id: string
          script_id: string
          added_at: string
        }
        Insert: {
          collection_id: string
          script_id: string
          added_at?: string
        }
        Update: {
          collection_id?: string
          script_id?: string
          added_at?: string
        }
      }
      referrals: {
        Row: {
          id: string
          referrer_id: string
          referred_id: string
          referral_code_used: string
          status: 'pending' | 'converted' | 'rewarded'
          reward_type: string | null
          reward_granted_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          referrer_id: string
          referred_id: string
          referral_code_used: string
          status?: 'pending' | 'converted' | 'rewarded'
          reward_type?: string | null
          reward_granted_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          referrer_id?: string
          referred_id?: string
          referral_code_used?: string
          status?: 'pending' | 'converted' | 'rewarded'
          reward_type?: string | null
          reward_granted_at?: string | null
          created_at?: string
        }
      }
      microlearning_tips: {
        Row: {
          id: string
          content: string
          category: string | null
          is_active: boolean
          display_count: number
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          content: string
          category?: string | null
          is_active?: boolean
          display_count?: number
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          content?: string
          category?: string | null
          is_active?: boolean
          display_count?: number
          created_by?: string | null
          created_at?: string
        }
      }
      ai_prompts: {
        Row: {
          id: string
          name: string
          type: 'generation' | 'conversation' | 'analysis' | 'objection'
          system_prompt: string
          user_prompt_template: string
          model: string
          temperature: number
          max_tokens: number
          is_active: boolean
          version: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          type: 'generation' | 'conversation' | 'analysis' | 'objection'
          system_prompt: string
          user_prompt_template: string
          model?: string
          temperature?: number
          max_tokens?: number
          is_active?: boolean
          version?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          type?: 'generation' | 'conversation' | 'analysis' | 'objection'
          system_prompt?: string
          user_prompt_template?: string
          model?: string
          temperature?: number
          max_tokens?: number
          is_active?: boolean
          version?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      ai_generation_log: {
        Row: {
          id: string
          user_id: string
          prompt_template_id: string
          type: 'generation' | 'conversation' | 'analysis'
          input_context: Json
          generated_content: string
          model_used: string
          tokens_used: number
          saved_as_script_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          prompt_template_id: string
          type: 'generation' | 'conversation' | 'analysis'
          input_context: Json
          generated_content: string
          model_used: string
          tokens_used: number
          saved_as_script_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          prompt_template_id?: string
          type?: 'generation' | 'conversation' | 'analysis'
          input_context?: Json
          generated_content?: string
          model_used?: string
          tokens_used?: number
          saved_as_script_id?: string | null
          created_at?: string
        }
      }
      sales_agenda: {
        Row: {
          id: string
          user_id: string
          agenda_date: string
          time_block: string
          action_type: string
          lead_id: string | null
          suggested_script_id: string | null
          completed: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          agenda_date: string
          time_block: string
          action_type: string
          lead_id?: string | null
          suggested_script_id?: string | null
          completed?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          agenda_date?: string
          time_block?: string
          action_type?: string
          lead_id?: string | null
          suggested_script_id?: string | null
          completed?: boolean
          created_at?: string
        }
      }
    }
    Functions: {
      calculate_level: {
        Args: { xp: number }
        Returns: string
      }
      add_xp: {
        Args: { user_id: string; amount: number }
        Returns: void
      }
      generate_referral_code: {
        Args: { user_id: string }
        Returns: string
      }
      admin_list_profiles: {
        Args: Record<string, never>
        Returns: Database['public']['Tables']['profiles']['Row'][]
      }
      admin_update_profile: {
        Args: { target_user_id: string; updates: Json }
        Returns: void
      }
    }
    Enums: {
      plan_type: 'starter' | 'pro' | 'premium' | 'copilot'
      role_type: 'user' | 'admin'
      tone_type: 'formal' | 'casual' | 'direct'
      level_type: 'iniciante' | 'vendedor' | 'closer' | 'topseller' | 'elite'
      lead_stage: 'novo' | 'abordado' | 'qualificado' | 'proposta' | 'fechado' | 'perdido'
      ai_prompt_type: 'generation' | 'conversation' | 'analysis' | 'objection'
      ai_log_type: 'generation' | 'conversation' | 'analysis'
      webhook_event_type: 'purchase' | 'upgrade' | 'cancel'
      referral_status: 'pending' | 'converted' | 'rewarded'
    }
  }
}
